### ISSUE TITLE
Update TOC post to reflect changes in how Pandoc handles Templates

### ISSUE THREAD

**Issue by stroebel** [vaclavsvejcar/svejcar-dev#4]
Pandoc changed how it handles Templates which made [your post](https://svejcar.dev/posts/2019/11/27/table-of-contents-in-hakyll/) on adding a TOC to your Hakyll site out of date. Please consider adding these changes to the post as your post seems to be the only post on this topic. 

There are two solutions that I have found: yours and [Jasper](https://github.com/jaspervdj/hakyll/blob/master/web/site.hs)'s.
```withTableOfContents :: WriterOptions -> WriterOptions
withTableOfContents options = options { writerNumberSections  = True
                                      , writerTableOfContents = True
                                      , writerTOCDepth        = 2
                                      , writerTemplate        = Just tocTemplate
                                      }
```
where `tocTemplate` is either
```
tocTemplate :: Template Text
tocTemplate = case runIdentity $ compileTemplate "" tmpl of
  Left  err      -> error err
  Right template -> template
 where
  tmpl = T.intercalate
    "\n"
    [ ""
    , "<div class=\"toc\"><div class=\"header\">Table of Contents</div>"
    , "$toc$"
    , "</div>"
    , "$body$"
    ]
```
or
```
tocTemplate =
  either error id $
    either (error . show) id $
      Pandoc.runPure $
        Pandoc.runWithDefaultPartials $
          Pandoc.compileTemplate "" "<div class=\"toc\"><div class=\"header\">Table of Contents</div>$toc$</div>$body$"
```

The former being your solution and the latter Jasper's.

I did not want to be presumptuous by making a pull request on your writing, but I do hope that you would update this.

Thank you.

**Comment by vaclavsvejcar** [comment]
@stroebel Hi, thanks for reporting this 👍 Probably I fixed it in the source code and forgot to update the article. I'll deploy fixed version of the article shortly.

**Comment by vaclavsvejcar** [comment]
I deployed new version of article where this issue is fixed. I also made some other minor corrections to the article. I also simplified the affected code little bit 🙂

```haskell
tocTemplate :: Template Text
tocTemplate = either error id . runIdentity . compileTemplate "" $ T.unlines
  [ "<div class=\"toc\"><div class=\"header\">Table of Contents</div>"
  , "$toc$"
  , "</div>"
  , "$body$"
  ]
```

**Comment by stroebel** [comment]
Fantastic, and thank you for the article.
